// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh2OYaseyO2WJPU_YiC9hZ4-tDRlfLHwI',
    appId: '1:461220268090:web:582acbe3e44b8b84184d03',
    messagingSenderId: '461220268090',
    projectId: 'skyer-d7aa1',
    authDomain: 'skyer-d7aa1.firebaseapp.com',
    storageBucket: 'skyer-d7aa1.appspot.com',
    measurementId: 'G-CQ42YDP02M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-4IFl1-i0GvaoN9H66_HR3UdQMy3Vaxs',
    appId: '1:461220268090:android:96562e9b7ea6b30f184d03',
    messagingSenderId: '461220268090',
    projectId: 'skyer-d7aa1',
    storageBucket: 'skyer-d7aa1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtYD22J7GnxzgGLZU8OG5HbrxztBd4dZc',
    appId: '1:461220268090:ios:2fa1a225c0345f25184d03',
    messagingSenderId: '461220268090',
    projectId: 'skyer-d7aa1',
    storageBucket: 'skyer-d7aa1.appspot.com',
    iosBundleId: 'com.example.skyer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtYD22J7GnxzgGLZU8OG5HbrxztBd4dZc',
    appId: '1:461220268090:ios:1e83dc47348bb95c184d03',
    messagingSenderId: '461220268090',
    projectId: 'skyer-d7aa1',
    storageBucket: 'skyer-d7aa1.appspot.com',
    iosBundleId: 'com.example.skyer.RunnerTests',
  );
}
